import { Student } from './student';
export const MockViewStudent: Student[] = [
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
  // {
  //   ID: 1,
  //   id_stu: 'a1',
  //   name_stu: 'abc',
  //   email: 'asdv@gmail.com',
  //   phoneNumber: '12345',
  // },
];
