import { StaffProfiles } from "./staff-profiles";
export const MockStaffProfiles: StaffProfiles[] = [
  // {id_staff: 'nv001', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv002', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv003', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv004', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv005', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv006', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv007', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv008', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv009', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv0010', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv0011', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv0012', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv0013', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv0014', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv0015', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv0016', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },
  // {id_staff: 'nv0017', fullName: 'Phạm Văn Pha', sex: 'nam', dateOfBirth: '29/8/2000', identityCard: '385823217', nation: 'Kinh', homeTown: 'Bạc Liêu', email: 'phampha8a3@gmail.com', phoneNumber: '0886088759', address: 'nguyễn chí thanh HCM', position: 'fullstack', department: 'IT', health: 'tốt', salary: 5000, coefficientSalary: 3.1, leaveDay: 10, education: 'HCMUNRE', skillLanguage: 'căn bản' },

]
