import { Teacher } from './teacher';

export const MockTeacher: Teacher[] = [
  // {
  //   ID: 1,
  //   id_tea: 'gv01',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 2,
  //   id_tea: 'gv02',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 3,
  //   id_tea: 'gv03',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 4,
  //   id_tea: 'gv04',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 5,
  //   id_tea: 'gv05',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 6,
  //   id_tea: 'gv06',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 7,
  //   id_tea: 'gv07',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 8,
  //   id_tea: 'gv08',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 9,
  //   id_tea: 'gv09',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 10,
  //   id_tea: 'gv010',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 11,
  //   id_tea: 'gv011',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 12,
  //   id_tea: 'gv012',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 13,
  //   id_tea: 'gv013',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 14,
  //   id_tea: 'gv014',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 15,
  //   id_tea: 'gv015',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 16,
  //   id_tea: 'gv016',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 17,
  //   id_tea: 'gv017',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 18,
  //   id_tea: 'gv018',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
  // {
  //   ID: 19,
  //   id_tea: 'gv019',
  //   name_tea: 'abc',
  //   type_tea: 'gv',
  //   email: 'gv@gmail.com',
  //   phone: '12345',
  // },
];
